"""creacion de tabla libros escritores

Revision ID: 121b12442285
Revises: 75a70a0b7a0a
Create Date: 2026-09-23 22:56:48.396452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121b12442285'
down_revision = '75a70a0b7a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libros_escritores',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('escritor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escritor_id'], ['escritores.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'escritor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libros_escritores')
    # ### end Alembic commands ###
