"""creacion de tabla prestamos y ejemplares

Revision ID: 88120cf6d62d
Revises: 121b12442285
Create Date: 2026-09-26 18:54:40.615948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88120cf6d62d'
down_revision = '121b12442285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejemplares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_inventario', sa.VARCHAR(length=100), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'PRESTADO', 'NO_DISPONIBLE', name='estadoejemplar'), nullable=True),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_prestamos', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ejemplar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ejemplar_id'], ['ejemplares.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamos')
    op.drop_table('ejemplares')
    # ### end Alembic commands ###
