"""editando tabla libros: se agrega columna: eliminado

Revision ID: 8f484bfe1c9f
Revises: 88120cf6d62d
Create Date: 2026-09-28 22:22:17.779043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f484bfe1c9f'
down_revision = '88120cf6d62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    # ### end Alembic commands ###
